version: '3.1'

services:
  db:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "5001:3306"
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=pronto_entregue
      - MYSQL_USER=prontouser
      - MYSQL_PASSWORD=0000