import {MigrationInterface, QueryRunner} from "typeorm";

export class sectionToSections1602438513601 implements MigrationInterface {
    name = 'sectionToSections1602438513601'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("DROP INDEX `IDX_3aecc6d707a2e8787b82bbc707` ON `options_groups`");
        await queryRunner.query("DROP INDEX `IDX_7f8103cfe175c66f1e5e8acfe2` ON `credit_balances`");
        await queryRunner.query("ALTER TABLE `order_options` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `order_options` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `order_options` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `options` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `options` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `options_groups` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `options_groups` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `order_option_groups` DROP FOREIGN KEY `FK_2d35f9d488137f53f6c0c76a9b1`");
        await queryRunner.query("ALTER TABLE `order_option_groups` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `order_option_groups` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `order_option_groups` CHANGE `orderProductId` `orderProductId` int UNSIGNED NULL");
        await queryRunner.query("ALTER TABLE `roles` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `roles` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `company_users` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `company_users` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `company_users` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `credit_balances` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `credit_balances` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `credit_history` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `credit_history` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `ratings` DROP FOREIGN KEY `FK_38bce3ebd84aa545a418c6b6e9c`");
        await queryRunner.query("ALTER TABLE `ratings` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `ratings` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `ratings` ADD UNIQUE INDEX `IDX_38bce3ebd84aa545a418c6b6e9` (`orderId`)");
        await queryRunner.query("ALTER TABLE `user_metas` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `user_metas` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `coupons` CHANGE `taxable` `taxable` decimal(10,2) NULL COMMENT 'Porcentagem do cupom que será pago pelo estabelecimento' DEFAULT 100");
        await queryRunner.query("ALTER TABLE `coupons` CHANGE `minValue` `minValue` decimal(10,2) NULL DEFAULT 0");
        await queryRunner.query("ALTER TABLE `coupons` CHANGE `maxValue` `maxValue` decimal(10,2) NULL DEFAULT 0");
        await queryRunner.query("ALTER TABLE `coupons` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `coupons` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `users` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `users` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `deliveries` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `deliveries` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `company_payment_methods` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `company_payment_methods` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `company_payment_methods` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `payment_methods` CHANGE `fee` `fee` decimal(10,2) NOT NULL DEFAULT 0");
        await queryRunner.query("ALTER TABLE `payment_methods` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `payment_methods` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `orders` DROP FOREIGN KEY `FK_cbeaba1d3093f972e9b89fe5042`");
        await queryRunner.query("ALTER TABLE `orders` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `orders` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `orders` ADD UNIQUE INDEX `IDX_cbeaba1d3093f972e9b89fe504` (`creditHistoryId`)");
        await queryRunner.query("ALTER TABLE `order_products` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `order_products` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `order_products` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `sales` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `sales` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `products` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `products` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `categories` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `categories` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `company_types` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `company_types` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `company_metas` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `company_metas` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `delivery_areas` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `delivery_areas` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `view_areas` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `view_areas` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `companies` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `companies` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `addresses` CHANGE `createdAt` `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `addresses` CHANGE `updatedAt` `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_38bce3ebd84aa545a418c6b6e9` ON `ratings` (`orderId`)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_cbeaba1d3093f972e9b89fe504` ON `orders` (`creditHistoryId`)");
        await queryRunner.query("ALTER TABLE `order_option_groups` ADD CONSTRAINT `FK_2d35f9d488137f53f6c0c76a9b1` FOREIGN KEY (`orderProductId`) REFERENCES `order_products`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `ratings` ADD CONSTRAINT `FK_38bce3ebd84aa545a418c6b6e9c` FOREIGN KEY (`orderId`) REFERENCES `orders`(`id`) ON DELETE SET NULL ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `orders` ADD CONSTRAINT `FK_cbeaba1d3093f972e9b89fe5042` FOREIGN KEY (`creditHistoryId`) REFERENCES `credit_history`(`id`) ON DELETE SET NULL ON UPDATE CASCADE");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `orders` DROP FOREIGN KEY `FK_cbeaba1d3093f972e9b89fe5042`");
        await queryRunner.query("ALTER TABLE `ratings` DROP FOREIGN KEY `FK_38bce3ebd84aa545a418c6b6e9c`");
        await queryRunner.query("ALTER TABLE `order_option_groups` DROP FOREIGN KEY `FK_2d35f9d488137f53f6c0c76a9b1`");
        await queryRunner.query("DROP INDEX `REL_cbeaba1d3093f972e9b89fe504` ON `orders`");
        await queryRunner.query("DROP INDEX `REL_38bce3ebd84aa545a418c6b6e9` ON `ratings`");
        await queryRunner.query("ALTER TABLE `addresses` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `addresses` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `companies` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `companies` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `view_areas` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `view_areas` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `delivery_areas` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `delivery_areas` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `company_metas` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `company_metas` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `company_types` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `company_types` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `categories` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `categories` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `products` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `products` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `sales` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `sales` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `order_products` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `order_products` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `order_products` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `orders` DROP INDEX `IDX_cbeaba1d3093f972e9b89fe504`");
        await queryRunner.query("ALTER TABLE `orders` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `orders` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `orders` ADD CONSTRAINT `FK_cbeaba1d3093f972e9b89fe5042` FOREIGN KEY (`creditHistoryId`) REFERENCES `credit_history`(`id`) ON DELETE SET NULL ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `payment_methods` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `payment_methods` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `payment_methods` CHANGE `fee` `fee` decimal(10,2) NOT NULL DEFAULT '0.00'");
        await queryRunner.query("ALTER TABLE `company_payment_methods` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `company_payment_methods` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `company_payment_methods` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `deliveries` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `deliveries` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `users` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `users` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `coupons` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `coupons` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `coupons` CHANGE `maxValue` `maxValue` decimal(10,2) NULL DEFAULT '0.00'");
        await queryRunner.query("ALTER TABLE `coupons` CHANGE `minValue` `minValue` decimal(10,2) NULL DEFAULT '0.00'");
        await queryRunner.query("ALTER TABLE `coupons` CHANGE `taxable` `taxable` decimal(10,2) NULL COMMENT 'Porcentagem do cupom que será pago pelo estabelecimento' DEFAULT '100.00'");
        await queryRunner.query("ALTER TABLE `user_metas` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `user_metas` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `ratings` DROP INDEX `IDX_38bce3ebd84aa545a418c6b6e9`");
        await queryRunner.query("ALTER TABLE `ratings` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `ratings` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `ratings` ADD CONSTRAINT `FK_38bce3ebd84aa545a418c6b6e9c` FOREIGN KEY (`orderId`) REFERENCES `orders`(`id`) ON DELETE SET NULL ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `credit_history` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `credit_history` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `credit_balances` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `credit_balances` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `company_users` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `company_users` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `company_users` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `roles` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `roles` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `order_option_groups` CHANGE `orderProductId` `orderProductId` int(10) UNSIGNED NULL");
        await queryRunner.query("ALTER TABLE `order_option_groups` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `order_option_groups` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `order_option_groups` ADD CONSTRAINT `FK_2d35f9d488137f53f6c0c76a9b1` FOREIGN KEY (`orderProductId`) REFERENCES `order_products`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `options_groups` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `options_groups` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `options` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `options` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `order_options` CHANGE `updatedAt` `updatedAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `order_options` CHANGE `createdAt` `createdAt` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `order_options` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("CREATE UNIQUE INDEX `IDX_7f8103cfe175c66f1e5e8acfe2` ON `credit_balances` (`userId`)");
        await queryRunner.query("CREATE UNIQUE INDEX `IDX_3aecc6d707a2e8787b82bbc707` ON `options_groups` (`maxSelectRestrain`)");
    }

}
